### ISSUE TITLE
There is no validation when entering an invalid container image name

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurecontainerapps#120]
**OS:** Win10/M1
**Build Version:** 20220520.7
**Regression:** Not a Regression

**Repro Steps:**
1. Right click one container app environment -> Select "Create Container App..." -> Enter a name for container app -> Select "Other public registry" -> Enter an invalid container image name.
2. Check whether there is a validation when entering an invalid container image name.

**Expect:**
There is a validation when entering an invalid container image name.

**Actual:**
1. There is no validation when entering an invalid container image name.
![image](https://user-images.githubusercontent.com/45614674/169509968-9ecc635c-43bb-4b83-b006-46c8a754ba96.png)
2. An error occurs if creating container app with this invalid image.
![image](https://user-images.githubusercontent.com/45614674/169510127-01494bee-5c6b-4d4d-8333-6490594019a5.png)

**Comment by bwateratmsft** [comment]
Yeah, I mentioned the same [here](https://github.com/microsoft/vscode-azurecontainerapps/pull/114#discussion_r877148683). We felt like it probably wasn't needed, because people would almost always be pasting the image name.

**Comment by nturinski** [comment]
> Yeah, I mentioned the same [here](https://github.com/microsoft/vscode-azurecontainerapps/pull/114#discussion_r877148683). We felt like it probably wasn't needed, because people would almost always be pasting the image name.

Closing as by-design.
