### ISSUE TITLE
The selected scaling's range does not change when the revision mode of the container app is multiple

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurecontainerapps#121]
**OS:** Win10/M1
**Build Version:** 20220520.7
**Regression:** Not a Regression

**Repro Steps:**

1. Right click a container app -> Choose Revision Mode -> Multiple.
2. Expand the container app -> Revisions -> Select a "test--**" -> Scaling -> Edit Scale Rule Setting with a valid range.
3. Check whether the selected scaling's range changes.

**Expect:**
The selected scaling's range changes.

**Actual:**
The selected scaling's range does not change and create a new "test--**" in the "Revision" node.
<img width="1064" alt="Screen Shot 2022-05-20 at 18 25 13" src="https://user-images.githubusercontent.com/62053665/169510149-3185fc73-73e1-49bd-94f6-2e20f1b44018.png">

**Comment by nturinski** [comment]
It's confusing, but this is actually expected behavior.  Whenever you edit the scaling rules, it actually makes a new revision.  So the changes aren't reflected in the old revision, just the new one that gets created.  The new one will now be the active one as well.
