### ISSUE TITLE
An error occurs after canceling the second deleting

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurecontainerapps#123]
**OS:** Win10/M1
**Build Version:** 20220520.7
**Regression:** Not a Regression

**Repro Steps:**

1. Right click a container app -> Delete Container App.
2. During deleting the container app -> Right click the container app again -> Delete Container App -> Click "**Cancel**" when popping up the prompt dialog.
    <img width="259" alt="Screen Shot 2022-05-20 at 19 19 40" src="https://user-images.githubusercontent.com/62053665/169517236-4b19ecbc-c0b2-4390-82d3-8d84c4c66644.png">
5. Check whether no error occurs.

**Expect:**
No error occurs.

**Actual:**
**An error occurs**.
<img width="438" alt="Screen Shot 2022-05-20 at 19 22 21" src="https://user-images.githubusercontent.com/62053665/169517648-d1274c66-1130-42e9-b200-d18232e46460.png">

**Comment by nturinski** [comment]
While the error is a bit strange, it makes sense since it was in the process of being deleted already. I will close this as wontfix unless we get user feedback about it.
