### ISSUE TITLE
An error occurs when executing "Edit Target Port" command from command palette

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurecontainerapps#143]
**OS:** All
**Build Version:** 20220706.3

**Repro Steps:**
1. F1 -> Azure Container Apps: Edit Target Port.
2. Check whether the "Select a resource" option pops up or not.

**Expect:**
The "Select a resource" option pops up.

**Actual:**
An error occurs.
![image](https://user-images.githubusercontent.com/45614674/177520826-832ee138-c181-4496-bb68-62056bb4732b.png)
 
**More Info:**
1. This issue also reproduces when executing "Edit Scale Rule Setting/Enable Ingress for Container App/Disable Ingress for Container App/Switch Ingress Visibility" command from command palette.
2. This issue does not reproduce when executing the above commands from context menu.

**Comment by v-xinda** [comment]
Verified on the latest build 20220908.8, an error "No matching resource found" occurs when executing "Edit Target Port/Disable Ingress for Container App/Switch Ingress Visibility" command from command palette.
<img width="537" alt="Screen Shot 2022-09-09 at 18 25 33" src="https://user-images.githubusercontent.com/57662131/189330326-cd24e78a-b9b2-45e6-9c42-0d7164433fef.png">

**Comment by MicroFish91** [comment]
First part was addressed by #251 

Will need to double check that `No matching resources found` error was fixed by the latest `.dev` update via CTI tests

**Comment by v-ruizh** [comment]
This issue does not reproduce on the main branch build 20230403.1, close it.
