### ISSUE TITLE
The revision mode is not updated in resource view after executing "Choose Revision Mode" command from command palette

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurecontainerapps#144]
**OS:** All
**Build Version:** 20220706.3

**Repro Steps:**
1. F1 -> Azure Container Apps: Choose Revision Mode... to change the revision mode for a container app.
2. Check whether the revision mode is updated in resource view or not.

**Expect:**
The revision mode is updated in resource view.

**Actual:**
The revision mode is not updated in resource view.

**More Info:**
Refresh can fix this issue.

**Comment by nturinski** [comment]
Fixed by #151
