### ISSUE TITLE
[Suggestion] It would be better to remove the extra "Container Apps" node

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurecontainerapps#150]
**OS:** All
**Build Version:** 20220706.3

**Repro Steps:**
1. Make sure the resource groups by Resource Type.
2. Install the Container app extension -> Expand the subscription.
3. Check whether there is no extra "Container Apps" node. 

**Actual:**
There is an extra "Container Apps" node. 
![image](https://user-images.githubusercontent.com/57662131/177529011-8bc35850-ecb2-47dd-a6ac-5b8d2ad163b3.png)

**Suggestion:**
It would be better to remove the extra "Container Apps" node. 

**More Info:**
The "Container Apps Environment" node contains the container apps.

**Comment by nturinski** [comment]
I plan on adding a setting that will take care of this problem.

By default, the Environment node will be displayed but the user can also display the Container Apps node as well.
