### ISSUE TITLE
It would be better to add a "+Create a secret" option in the step "Choose a secret reference" [Secret management]

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurecontainerapps#186]
**OS:** All
**Build Version:** 20220908.8
**Regression:** Not a Regression

**Repro Steps:**
1. Expand one container app **without any secrets** -> Right click "Scale Rules" node and select "Add Scale Rules..." -> Enter a name for the new scale rule -> Select "Azure queue" -> Enter a name for the queue -> Enter a queue length -> Press Enter.
2. Check whether there is a "+Create a secret" option in the next step "Choose a secret reference".

**Actual:**
There is no "+Create a secret" option in the next step "Choose a secret reference", an error occurs when loading the secret.
![image](https://user-images.githubusercontent.com/45614674/189289206-e1832358-76d6-482b-ac4e-f929046e3913.png)

**Suggestion:**
It would be better to add a "+Create a secret" option in the step "Choose a secret reference", otherwise the user need to add a secret in the portal.

**More Info:**
The new scale rule with "Azure queue" selecting can be created successfully if there is at least one secret in the container app.

**Comment by MicroFish91** [comment]
This is a good suggestion.  We will look at addressing this in the next iteration of updates to Scale Rules (we are also looking into batch-adding rules in the future so as not to trigger so many automatic revisions).

**Comment by v-ruizh** [comment]
This issue has been fixed on extension build 20230920.3.
