### ISSUE TITLE
Error creating new Container App

### ISSUE THREAD

**Issue by BigMorty** [microsoft/vscode-azurecontainerapps#19]
**Repro Steps**
- Right clicked on my new CA env I just created and selected 'Create Container App...'
- Name - 'first-app'
- Cont Reg - ACR - 'mikemortACR'
- Repository - 'orderproc'
- Tag = '3.0'
- HTTP endpoint - 'Enable'
- Traffic - 'External'
- Port - '80'

**Received the following error...**
Error: The following field(s) are either invalid or missing. Invalid value: "orderproc-3.0": Invalid Name: Per RFC 1123 name must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character (e.g. 'my-name',  or '123-abc', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?'): template.containers.

I tried a few other attempts, the pattern I see is it fails if the tag I select is something like 3.0 or 2.2. If I select a tag without a period in it, it works.

**Comment by anthonychu** [comment]
Likely because the `.` creates an invalid hostname.

Also need to verify other name requirements. For instance, there's a limit of 2–20 characters enforced in VS Code but longer names are allowed.
