### ISSUE TITLE
Centralize `localize` strings into constants

### ISSUE THREAD

**Issue by MicroFish91** [microsoft/vscode-azurecontainerapps#199]
Potential backlog candidate....

Would it be worth centralizing our `localize` strings into reusable constants so that we don't accidentally override existing ID's?  Structure could look something like this in `constants.ts`:

![image](https://user-images.githubusercontent.com/40250218/190029816-a2a3b6e3-5304-491d-83f5-572d435b9f51.png)

[From demo branch](https://github.com/microsoft/vscode-azurecontainerapps/compare/main...mwf/centralize-localize)

**Comment by alexweininger** [comment]
Definitely something to consider. 

I think our current philosophy is to only make something a reusable constant once it is needed in two places. However, as you point out, it's hard to keep track of when things are used in two places.

I've also seen extensions put all their [messages in a single file](https://github.com/gitkraken/vscode-gitlens/blob/main/src/messages.ts). This could help us keep track of localized strings, and also clean up some code.

**Comment by MicroFish91** [comment]
Closing in response to new information/Brandon's comment [here](https://github.com/microsoft/vscode-azurefunctions/pull/3390#discussion_r1007123108) regarding new `l10n` API.
