### ISSUE TITLE
There is an "Enable Ingress" option when executing "Disable Ingress" command for a disabled Ingress container app 

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurecontainerapps#201]
**OS:** All
**Build Version:** 20220914.3

**Repro Steps:**
1. Disable Ingress for one container app.
2. F1 -> Azure Container Apps: Disable Ingress for Container App -> Select the container app environment -> Select the container app which Ingress is disabled.
3. Check whether an error occurs or not.

**Expect:**
An error occurs.
![image](https://user-images.githubusercontent.com/45614674/190097546-e0d1c3fa-f656-4496-9d2f-b483ffeebb5f.png)

**Actual:**
No error occurs and the next step is "Enable Ingress".
![image](https://user-images.githubusercontent.com/45614674/190097628-f9ab66cc-7389-4257-8c72-ecf8823bf873.png)

**Comment by MicroFish91** [comment]
I believe this is fixed now, could you please confirm, thank you!

**Comment by MicroFish91** [comment]
I believe this is fixed, could you please check and confirm, thank you!

**Comment by v-ruizh** [comment]
Verified on build 20231006.4, it is no longer reproduced.
