### ISSUE TITLE
Not all tags are shown for a repo

### ISSUE THREAD

**Issue by BigMorty** [microsoft/vscode-azurecontainerapps#21]
- Right click on existing app and select 'Deploy image to Container App'
- Registry - 'ACR' - 'mikemortACR'
- Repository - Choose one with multiple tags

**Issue: Only most recent tag is shown** - Should see 4 tags for this repo

![image](https://user-images.githubusercontent.com/947510/151305254-7fc30443-ee4d-485e-9c08-37dcd1053a73.png)

**Comment by nturinski** [comment]
Heeey @BigMorty!

Do you happen to know if the other tags have some invalid characters or some other pattern (maybe associated with a different repo or anything else) that could be causing this behavior?  I haven't run into this myself and have registries with multiple tags, so just wondering if you had any more insight.

Could you list the other tags for me?

**Comment by BigMorty** [comment]
Here is an example of what I see in the Docker explorer for the orderproc image in my ACR:
![image](https://user-images.githubusercontent.com/947510/153108169-68d912e5-9aea-41af-9e83-b8a1b5d6c3cf.png)

Here is what I see when I go to create a container app using orderproc:
![image](https://user-images.githubusercontent.com/947510/153108220-b6b04dfe-98b1-4065-a420-131454159269.png)
