### ISSUE TITLE
Pop up an error when refreshing the tree view contains a deleted container app environment

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurecontainerapps#214]
**OS:** Win10
**Build Version:** 20221012.1
**Regression:** Not a regression

**Repro Steps:**
1. Create a new container apps environment.
2. Delete the above container apps environment in the portal.
3. Back to VS Code -> Refresh the Resource tree view.
4. Check whether the deleted container apps environment disappears from the tree view.

**Expect:**
The deleted container apps environment disappears from the tree view.

**Actual:**
1. The deleted container apps environment disappears from the tree view.
2. Pop up errors.
![image](https://user-images.githubusercontent.com/57662131/195788180-d6d6cbfb-db93-481f-b881-e991474f6047.png)
![image](https://user-images.githubusercontent.com/57662131/195800847-507a66e7-2296-455a-a388-91acfedf680c.png)

**More Info:**
This issue doesn't reproduce after deleting a container app.

**Comment by alexweininger** [comment]
Closing because this is closely related to #256, and the behavior has changed slightly since this issue was opened.
