### ISSUE TITLE
It takes more than 13 mins to delete a container apps environment

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurecontainerapps#225]
**OS:** Win10
**Build Version:** 20221123.1

**Repro Steps:**
1. Create a new container apps environment.
2. Delete the above container apps environment.
3. Check whether succeed to delete the container apps environment in 2 mins.

**Expect:**
Succeed to delete the container apps environment in 2 mins.

**Actual:**
It takes more than 13 mins to delete a container apps environment.

**More Info:**
1. A container apps environment can be created in 2 mins.
2. It takes more than 10 mins to delete a container apps environment from portal.

**Comment by nturinski** [comment]
It seems like this is just a long running operation. 
We may want to let users know ahead of time that this could take a while. 
Or we may not want to wait for it to delete and just remove it from the tree even before it's actually deleted.

**Comment by MicroFish91** [comment]
We might need to inform the user that this process may take a while to finish running, possibly through an update to the Activity Log description
