### ISSUE TITLE
Web extension runtime issues

### ISSUE THREAD

**Issue by nturinski** [microsoft/vscode-azurecontainerapps#239]
- [x] `Container Apps: Create Container App...`
  - Fails on the list repository step. It looks like it's a CORS access problem
  - > For accessing web resources, the [Fetch](https://developer.mozilla.org/docs/Web/API/Fetch_API) API must be used. Accessed resources need to support [Cross-Origin Resource Sharing](https://developer.mozilla.org/docs/Web/HTTP/CORS) (CORS) - from https://code.visualstudio.com/api/extension-guides/web-extensions
  -Blaming it on the propagation. . .
- [x] `Container Apps: Revision Activate/Deactivate/Restart`
  - Doesn't show an error, but seems like nothing happens
- [x] `Container Apps: Create Container Apps Environment`
  - Same issue as Azure: Create Resource
- [x] `Container Apps: Edit Scaling Range`
  - Weird error-- might be T2 SDK related
- [x] `Container Apps: Edit Target Port`
  - undefined property-- probably T2 SDK related
- [x] `Container Apps: Open Console in Portal`
  - Same as `Azure: Open in Portal`
- [ ] `Container Apps: Update Image...`
  - Same issue as Container Apps: Create Container App
- [x] `Container Apps: Switch Ingress Visibility`
  - Same issue as Container Apps: Edit Scaling Range

**Comment by MicroFish91** [comment]
I think `Open Console in Portal` works now with Megan's fixes for `Azure: Open in Portal`.  
https://github.com/microsoft/vscode-azureresourcegroups/pull/551

**Comment by MicroFish91** [comment]
- It looks like the `Open Console in Portal` and `Open in Portal` commands were fixed by Megan's PR https://github.com/microsoft/vscode-azureresourcegroups/pull/551

- Edit Scaling Range looks like it might be working now.

- Switch Ingress Visibility looks like it might be working now.
