### ISSUE TITLE
Error occurs whenever first CAE is deleted

### ISSUE THREAD

**Issue by motm32** [microsoft/vscode-azurecontainerapps#240]
_Seems to be related to v2 migration_ 

When the first CAE in the tree is deleted this error occurs:
![image](https://user-images.githubusercontent.com/59709511/216471321-22c3f055-65e4-4325-aa2d-67917838de6e.png)

**Notes**:
- This does not occur if any CAE other than the first is deleted 
- In the tree view all CAE's will disappear from the list and you have to refresh the whole tree view in order to see undeleted CAE's.

**Comment by alexweininger** [comment]
Can confirm that it only happens when deleting the first CAE... so weird

**Comment by alexweininger** [comment]
I've also encountered an issue where it fails to create a CAE with the same name of a recently deleted CAE. That makes me think that this is an issue with deleted resources sticking around after they've been deleted.

<img width="452" alt="image" src="https://user-images.githubusercontent.com/12476526/216489596-d2132b43-56c7-45f9-a6b3-47dcebefb36c.png">

**Comment by alexweininger** [comment]
Closing in favor of #256, since #256 has updated error info that includes the recent error handling changes.
