### ISSUE TITLE
The created container app environment is focused need to wait about 3 seconds after clicking "Click to view resource" in Activity Log window

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurecontainerapps#255]
**OS:** All
**Azure Container Apps Build Version:** 20230213.10
**Azure Resource Group Build Version:** 20230213.13
**Regression:** Not a regression

**Repro Steps:**
1. Create a container app environment -> Click "Click to view resource" in Activity Log window.
2. Check whether the created container app environment is focused immediately.

**Expect:**
The created container app environment is focused immediately.

**Actual:**
The created container app environment is focused need to wait about 3 seconds.

**Comment by alexweininger** [comment]
This is just a result of how we've implemented reveal in the new architecture. It is expected.
