### ISSUE TITLE
Image not scaling well

### ISSUE THREAD

**Issue by BigMorty** [microsoft/vscode-azurecontainerapps#26]
Here is what the extension image looks like on my machine.I tried with different monitors at different resolution and scale percentages, always looks the same.

![image](https://user-images.githubusercontent.com/947510/153312798-7926cd60-e8a8-4d83-bc4d-a514a6c6595b.png)

**Comment by nturinski** [comment]
Mike, I think something is going wrong with your eyes... 👀

Just kidding, thanks for filing this.  This is something that we've hilariously noted as well and I'll be sure to fix it

**Comment by BigMorty** [comment]
😂😂😂
