### ISSUE TITLE
[Suggestion] It would be better to change the description of the option to "Enter a name with tag..." 

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurecontainerapps#301]
**OS:** Win 10
**Build Version:** 20230326.1
**Regression:** Not a Regression

**Repro Steps:**
1. Open a project in VS Code which includes Dockerfile in it.
2. Select "Build from project remotely using Azure Container Registry" to create a container app -> Select an Azure Container Registry -> Select the default "Dockerfile" in the project folder.
3. Check the description for the next step.

**Actual:**
The description for the next step is "Enter a name for the image...".
![image](https://user-images.githubusercontent.com/45614674/227872222-b891f334-8735-45a9-b3f1-99df3f877fd4.png)

**Suggestion:**
It would be better to change the description to "Enter a name **with tag**...", like the below one.
![image](https://user-images.githubusercontent.com/45614674/227872490-dd17c0ae-0885-4a5c-beb4-8c97ef789e56.png)

**Comment by alexweininger** [comment]
We'll probably redesign the wizard and remove the step in the future so we'll leave this as-is for now.
