### ISSUE TITLE
There is no image source "Use quickstart image" when deploying an image to container app

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurecontainerapps#302]
**OS:** Win 10
**Build Version:** 20230326.1
**Regression:** Not a Regression

**Repro Steps:**
1. Right click one container app -> Select "Deploy to Container App...".
2. Check whether there is an image source "Use quickstart image" or not.

**Expect:**
There is an image source "Use quickstart image", like the below one.
![image](https://user-images.githubusercontent.com/45614674/227882119-4038f987-8197-4ecd-a2be-db69a4a6b5ce.png)

**Actual:**
There is no image source "Use quickstart image".
![image](https://user-images.githubusercontent.com/45614674/227881857-f63389f2-0ba3-49c5-92e8-10362fb6bd5f.png)

**Comment by MicroFish91** [comment]
Closing this one as by-design.  We only offer the quickstart image during creation.  It's mainly there for people to quickly demo ACA functionality
