### ISSUE TITLE
Error message for activating a revision that's already active is weird

### ISSUE THREAD

**Issue by alexweininger** [microsoft/vscode-azurecontainerapps#306]
<img width="490" alt="image" src="https://user-images.githubusercontent.com/12476526/228384402-0bcf50e0-c850-4ddf-93fb-16fb9e210fbc.png">

Why is there an `!` and a `.`? 😄

**Comment by MicroFish91** [comment]
Might be a duplicate of #297

**Comment by alexweininger** [comment]
Duplicate of #297
