### ISSUE TITLE
Deploy to a container app via connected GitHub repository and enable CI

### ISSUE THREAD

**Issue by nturinski** [microsoft/vscode-azurecontainerapps#313]
Similar to how to SWA does it, we want to hook up the user's GitHub repository so that whenever they push a new commit to it, it will automatically update the container app.

**Comment by MicroFish91** [comment]
Related tracking: https://github.com/microsoft/azure-container-apps/issues/530

**Comment by MicroFish91** [comment]
PR roadmap:
- [ ] Scaffold `connectToGitHub` and add wizard steps to obtain the GitHub org, repository, and branch <b>(current)</b>
- [ ] Finish the rest of the `non-Octokit-related` support for the command
- [ ] Add `Actions` tree node & children, similar to SWA
- [ ] Add a disconnect command
- [ ] Add more robust service principal selection/creation
- [ ] Convert GitHub work to shared package

**Comment by MicroFish91** [comment]
Have been blocked for a little while on waiting for the OIDC related SDK updates, see checklist above for more context**
