### ISSUE TITLE
Succeed to deploy an image of "Docker Hub registry" to a container app which created with an ACR image

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurecontainerapps#318]
**OS:** All
**Build Version:** 20230329.6
**Regression:** Previous Build

**Repro Steps:**
1. Create one container app with an image of "Azure Container Registry".
2. Change the revision mode of the above container app to multiple.
3. Right click the container app and execute "Deploy to Container App..." action with an existing image of "Docker Hub Registry".
4. Check whether fails to deploy the image to container app with an error.

**Expect:**
Fail to deploy the image to container app with an error.
![image](https://user-images.githubusercontent.com/45614674/228781772-974c9363-6638-487d-b578-e6cba2c48902.png)

**Actual:**
Succeed to deploy the image to container app.

**More Info:**
This issue does not reproduce on the older main branch build 20230323.1.

**Comment by nturinski** [comment]
I think this is by-design. 

I'm not sure why this wasn't working before. We were probably not preserving the registries when we created a new revision.  However, we shouldn't have been deleting the registry when we are adding images to a container app. It is valid to have multiple registries attached to one container app.
