### ISSUE TITLE
There is no error message after executing "Azure Container Apps: Activate Revision" command for one container app which the revision mode is "Single"

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurecontainerapps#320]
**OS:** All
**Build Version:** 20230329.6
**Regression:** Previous release

**Repro Steps:**
1. F1 -> Azure Container Apps: Activate Revision -> Select a container app which the revision mode is "Single".
2. Check whether there is an error message.

**Expect:**
There is an error message.
<img width="450" alt="Screenshot 2023-03-30 at 17 33 06" src="https://user-images.githubusercontent.com/57662131/228794067-b3364a95-1ca2-4631-9722-1352bccf0ecb.png">

**Actual:**
There is no error message.

**More Info:**
This issue also reproduces after executing "Deactivate Revision/Restart Revision" command from command palette.

**Comment by motm32** [comment]
Could you try this again with a different image? I was experiencing this issue but found out it was because my image was no longer in my Container Registry. After making a new image I no longer ran into this issue.

**Comment by motm32** [comment]
I can't seem to reproduce this. Could you try again with a different image?

**Comment by v-xinda** [comment]
@motm32  Verified this issue on the latest main build 20230331.3., it doesn't reproduce.
