### ISSUE TITLE
An error occurs when restarting an inactive revision

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurecontainerapps#322]
**OS:** All
**Build Version:** 20230329.6

**Repro Steps:**
1. Change one container app revision mode to "Multiple". 
2. Expand the Revision node and execute "Deactivate Revision" action for one revision.
3. Execute "Restart Revision" action for the above inactive revision.
4. Check whether succeeds to restart an inactive revision or not.

**Expect:**
Succeed to restart an inactive revision.

**Actual:**
An error occurs when restarting an inactive revision.
![image](https://user-images.githubusercontent.com/45614674/228808909-1e8e0afa-8b6b-411e-946c-1fc0d52a3f8e.png)

**Comment by motm32** [comment]
Could you try this again with a new image? I was running into this issue but found out it was because my image had been deleted from my Container Registry. After creating a new issue I no longer got this error.

**Comment by MicroFish91** [comment]
Personally, I'm still able to repro :(

I can take the exact same revision and restart it when active and it works.  When I de-activate and click restart it errors.
