### ISSUE TITLE
There is no action "Connect to GitHub Repository..." in the context menu of container app

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurecontainerapps#359]
**OS:** Win 10
**Build Version:** 20230503.4
**Regression:** Not a Regression

**Repro Steps:**
1. Right click one container app and check its context menu.
2. Check whether there is an action "Connect to GitHub Repository..." in the context menu.

**Expect:**
There is an action "Connect to GitHub Repository..." in the context menu.

**Actual:**
There is no action "Connect to GitHub Repository..." in the context menu.
![image](https://user-images.githubusercontent.com/45614674/236142459-81f5f84f-76e0-426e-a8eb-7d9bdba8c68c.png)

**More Info:**
There is a command "Azure Container Apps: Connect to GitHub Repository..." in command palette.
![image](https://user-images.githubusercontent.com/45614674/236142361-92205839-81d5-4541-bcaf-4b43ca7d77f5.png)

**Comment by MicroFish91** [comment]
Full implementation coming soon/in the works 😊

**Comment by MicroFish91** [comment]
Closed by https://github.com/microsoft/vscode-azurecontainerapps/pull/363

PR above added an Actions node to connect from via the tree view.
We also have the command available through the command palette from one of the previous PRs.
