### ISSUE TITLE
An error occurs when entering "04" as the number of concurrent requests during adding scale rule

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurecontainerapps#368]
**OS:** Win 10
**Build Version:** 20230510.5
**Regression:** Not a Regression

**Repro Steps:**
1. F1 -> Select "Azure Container Apps: Add Scale Rule..." -> Select a container app environment -> Select a container app -> Select a revision -> Enter a name for the new scale rule -> Select "HTTP scaling" -> Enter "04" as the number of concurrent requests.
2. Check whether no error occurs or not.

**Expect:**
No error occurs when entering "04" as the number of concurrent requests.

**Actual:**
An error occurs when entering "04" as the number of concurrent requests.
![image](https://github.com/microsoft/vscode-azurecontainerapps/assets/45614674/c1da6cff-3cb3-49f2-ab10-16b3bbdb2128)

**More Info:**
1. This issue also reproduces when entering "**4.0**" as the number of concurrent requests in VS Code.
2. This issue does not reproduce when entering "**04/4.0**" as the number of concurrent requests in portal.
![image](https://github.com/microsoft/vscode-azurecontainerapps/assets/45614674/cab6f303-a6e0-4b86-ad49-90ecc0a30ee6)

**Comment by alexweininger** [comment]
This is uncommon enough that we won't fix it.
