### ISSUE TITLE
[GitHub Codespaces] Fail to connect to a GitHub repository for a container app

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurecontainerapps#387]
**Environment:** Remote Codespaces 
**Build Version:** 20230613.3
**Regression:** Not a Regression

**Repro Steps:**
1. Create a new container app -> Expand it -> Expand "Configurations" node.
2. Expand "Actions" node -> Click "Connect to a GitHub Repository..." -> Select an organization -> Select a repository -> Select a branch -> Type the default relative location -> Select an azure container registry -> Select a repository -> Type a service principal ID -> Type a service principal secret.
3. Check whether succeeds to connect to a GitHub repository.

**Expect:**
Succeed to connect to a GitHub repository.

**Actual:**
Fail to connect to a GitHub repository.
![image](https://github.com/microsoft/vscode-azurecontainerapps/assets/57662131/4ab8ace2-61a5-47f3-925a-d535ff30cc93)

**More Info:**
This issue doesn't reproduce on the Local Codespaces environment and non-Codespaces environment.

**Comment by MicroFish91** [comment]
We bump the user out to the portal now due to auth limitations for creating service principals in VS Code.  This likely no longer applies, can you please confirm? Thank you!

**Comment by v-xinda** [comment]
@MicroFish91  Verified this issue using the latest main branch build 20230806.1. No error occurs after executing "Connect to a GitHub Repository..." action under the "Actions" node. 

But the "**con1 | Continuous deployment**" web page opens after clicking "Connect to a GitHub Repository..." action under the "Actions" node. 
![image](https://github.com/microsoft/vscode-azurecontainerapps/assets/57662131/949e7f2a-8738-4e84-a6b7-0640a5343fb7)

In non-Codespaces environment, the above issue (The "**con1 | Continuous deployment**" web page opens) also reproduces for now.

**Comment by MicroFish91** [comment]
Seems like the original error is no longer reproducing, above comment indicates behavior that is matching our new design.
