### ISSUE TITLE
Pop up a prompt to select a subscription/container apps environment when executing "Activate/Deactivate Revision" action continuously

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurecontainerapps#388]
**OS:** Win 10
**Build Version:** 20230613.3
**Regression:** Not a Regression

**Repro Steps:**
1. Make sure two subscriptions are selected.
2. Create a new container -> Right click it -> Click "Choose Revision Mode..." -> Select "Multiple".
3. Make sure there are more than two replicas and the replicas are "Inactive".
4. Right click the replica -> Click "Activate Revision".
5. Right click another replica immediately and click "Activate Revision".
6. Check whether another replica is "Activating...".

**Expect:**
Another replica is "Activating...".

**Actual:**
Pop up a prompt to select a subscription.
![actual](https://github.com/microsoft/vscode-azurecontainerapps/assets/57662131/351a8d35-ef95-414f-b96a-ac274bc4ba1d)

**More Info:**
1. This issue also reproduces when executing "Deactivate Revision" action.
2. It will prompt to select a container apps environment if only one subscription is selected.
![image](https://github.com/microsoft/vscode-azurecontainerapps/assets/57662131/bc3d6c39-cb45-4de7-af94-44c28b364a79)

**Comment by alexweininger** [comment]
Edge case
