### ISSUE TITLE
Add a deploy code to Container Apps command (with Dockerfile)

### ISSUE THREAD

**Issue by anthonychu** [microsoft/vscode-azurecontainerapps#40]
Same as deploy image, but allow selection of a dockerfile. Then use the ACR build command to build the image remotely in the registry.

Requires:
* Docker extension
* User is signed into Azure

Inputs:
* Location of a dockerfile
* Optionally, the docker build context (default to the folder of the dockerfile)
* Select or create container registry
* The image name and tag (the Docker extension defaults one based on the ACR build ID)
* Select or create container app (if the Dockerfile has an EXPOSE command, assume app needs an ingress and use its value as the port)
* Select or create container Apps environment

Consider saving this info in workspace settings to make it easier when deploying the app next time.

**Comment by nturinski** [comment]
Fixed by #292
