### ISSUE TITLE
There is no "Azure Container Apps" button in the WORKSPACE view

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurecontainerapps#408]
**OS:** Win10
**Build Version:** 20230717.1
**Regression:** Previous build (20230707.1)

**Repro Steps:**

1. Install the Azure Container Apps extension by VSIX.
2. Navigate to AZURE view.
3. Check the WORKSPACE view.

**Expect:**
There is an "Azure Container Apps" button in the WORKSPACE view.
![image](https://github.com/microsoft/vscode-azurecontainerapps/assets/57662131/52a88c6e-6370-4e60-a5f1-1b20749fca4e)

**Actual:**
There is no "Azure Container Apps" button in the WORKSPACE view.
![image](https://github.com/microsoft/vscode-azurecontainerapps/assets/57662131/f8a077da-c3ba-475c-8361-07197d4e5563)

**More Info:**
This issue doesn't reproduce on the main branch build 20230707.1.

**Comment by alexweininger** [comment]
This is by design.

**Comment by nturinski** [comment]
Should this be by-design? There is are the "Create Container Apps..." and "Create Container Apps Environment" commands to think about, but also we have "Deploy to Container App..."still there which will keep the cloud icon on the toolbar.
