### ISSUE TITLE
There is an extra "..." for the action "Update Container App Image......" in the context menu

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurecontainerapps#409]
**OS:** Win10
**Build Version:** 20230717.1
**Regression:** Not a regression

**Repro Steps:**

1. Create a container app -> Right click it.
2. Check the context menu.

**Expect:**
There is no extra "..." for the action "Update Container App Image......".

**Actual:**
There is an extra "..." for the action "Update Container App Image......".
![image](https://github.com/microsoft/vscode-azurecontainerapps/assets/57662131/f480d923-6c34-446b-961d-28b00c145d6c)

**Comment by MicroFish91** [comment]
Ended up fixing this in #405
