### ISSUE TITLE
The confused notification "Completed installing Azure Account extension from VSIX" shows after installing Azure Container Apps extension

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurecontainerapps#412]
**OS:** Win 10
**Build Version:** 20230720.1

**Repro Steps:**
1. Make sure there is no Azure Account extension in VS Code.
2. F1 -> Extensions: Install from VSIX... -> Select the .vsix for **Azure Container Apps** extension to install.
3. Check whether the correct notification "Completed installing Azure Container Apps extension from VSIX" shows.

**Expect:**
The correct notification "Completed installing **Azure Container Apps** extension from VSIX" shows.
![image](https://github.com/microsoft/vscode-azurecontainerapps/assets/45614674/8a048844-459a-4228-a0b8-c5c7f1d540c2)

**Actual:**
The confused notification "Completed installing **Azure Account** extension from VSIX" shows.
![image](https://github.com/microsoft/vscode-azurecontainerapps/assets/45614674/01a1c4c8-1784-4c48-9c87-dbbf460b33ea)

**More Info:**
1. This issue also reproduces after installing Azure Databases/Azure Functions/App Service/Azure Resource/Azure VM extensions without Azure Account extension installed previously.
2. This issue does not reproduce if Azure Account and Azure Resource extensions were installed previously.

**Comment by MicroFish91** [comment]
Perhaps the first extension to finish is the Azure Account extension, and the other pop-ups after are being stifled somehow?  Will need to investigate further

**Comment by MicroFish91** [comment]
We are deprecating Azure Account soon + it's likely that the extension window is being hidden and can be viewed through the bell icon at the bottom right.  We will close this as low impact.
