### ISSUE TITLE
Fail to add a secret which name contains "."

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurecontainerapps#421]
**OS:** Win 10/Mac
**Build Version:** 20230802.2
**Regression:** Not a Regression

**Repro Steps:**
1. Right click "Secrets" node -> Select "Add Secret..." -> Enter a name "test." as the secret name.
2. An error message shows. 
![image](https://github.com/microsoft/vscode-azurecontainerapps/assets/45614674/ebed537c-20f4-46d3-9254-b991fb98066a)
3. Enter a name "test.one" as the secret name.
4. Check whether succeeds to add a secret or not.

**Expect:**
Succeed to add a secret which name contains ".".

**Actual:**
Fail to add a secret which name contains ".".
![image](https://github.com/microsoft/vscode-azurecontainerapps/assets/45614674/de82075b-3ae0-41d9-a4c1-c4877a3dc2fa)

**More Info:**
This issue also reproduces in portal.

**Comment by MicroFish91** [comment]
Oh interesting, good catch!

I originally modeled the rules after the portal which says:
![image](https://github.com/microsoft/vscode-azurecontainerapps/assets/40250218/79bb78d6-c6c3-43b4-bf6a-3f1f32f24120)

If I'm reading that correctly, that means the portal also has validation logic that doesn't match up with the servers.  Should be an easy fix for us though
