### ISSUE TITLE
The container app is still connected to GitHub repo after executing "Disconnect from Repo" command

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurecontainerapps#422]
**OS:** Win 10/Mac
**Build Version:** 20230802.2

**Repro Steps:**
1. Execute "Connect to a GitHub Repository..." command for a container app.
2. Execute "Disconnect from Repo" command for the above container app.
3. Check whether the container app is disconnected from GitHub repo in Azure view.

**Expect:**
The container app is disconnected from GitHub repo in Azure view.
![image](https://github.com/microsoft/vscode-azurecontainerapps/assets/45614674/423e45f3-79e1-48b8-8e1a-613233d9e461)

**Actual:**
The container app is still connected to GitHub repo in Azure view.
![image](https://github.com/microsoft/vscode-azurecontainerapps/assets/45614674/f31e3411-dd91-4c89-b472-ea3f63db83b9)

**More Info:**
Refresh the Azure view can fix this issue.

**Comment by MicroFish91** [comment]
I haven't been able to reproduce this - mine is refreshing automatically after disconnecting.  Is this still reproducing after the latest GitHub changes we made?

**Comment by v-ruizh** [comment]
This issue does not reproduce on the latest build 20230813.1, close it.
