### ISSUE TITLE
Investigate new v2 environment and ensure extension deploy compatibility

### ISSUE THREAD

**Issue by MicroFish91** [microsoft/vscode-azurecontainerapps#429]
<img width="481" alt="image" src="https://github.com/microsoft/vscode-azurecontainerapps/assets/40250218/f598f0dd-05d4-4ec4-843f-8783f27b9ace">

**Comment by motm32** [comment]
Here is the error that pops up when creating a new container app using the new preview plan: 
![image](https://github.com/microsoft/vscode-azurecontainerapps/assets/59709511/94c5e559-6511-4145-bdec-dd3292b06533)

**Comment by MicroFish91** [comment]
Anthony mentioned they _may_ be generating a new SDK with 2023-05-01 API version
