### ISSUE TITLE
[Suggestion] It would be better to keep consistently for the last tooltip of "Start Streaming Logs..." and "Stop Streaming Logs..."

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurecontainerapps#436]
**OS:** Win 10
**Build Version:** 20230815.2
**Regression:** Not a Regression

**Repro Steps:**
1. Create one container app -> Right click one container app -> Select "Start Streaming Logs..." -> Select a replicas -> The next tooltip is "Select a container".
![image](https://github.com/microsoft/vscode-azurecontainerapps/assets/45614674/eaba2b58-a4cc-4782-964f-0f139a2003e8)
2. Select the container to start the command "Start Streaming Logs...".
3. Right click the above container app and select "Stop Streaming Logs...".
4. Check whether the last tooltip for "Stop Streaming Logs..." is consistent with "Start Streaming Logs...".

**Actual:**
The last tooltip for "Stop Streaming Logs..." is "Select a stream" instead of "Select a container".
![image](https://github.com/microsoft/vscode-azurecontainerapps/assets/45614674/21c8e561-8725-42d1-8522-7fc439efad67)

**Suggestion:**
It would be better to keep consistently for the last tooltip of "Start Streaming Logs..." and "Stop Streaming Logs...".

**Comment by MicroFish91** [comment]
The stream is the correct modifier here, it just so happens to match the container name.
