### ISSUE TITLE
There is no prompt "No matching resources found" when selecting an empty Azure Container Registry

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurecontainerapps#444]
**OS:** Win10
**Build Version:** 20230903.1
**Regression:** Not a Regression

**Repro Steps:**
1. F1 -> Execute "Azure Container Apps: Create Azure Container Registry..." command to create an Azure Container Registry.
2. Right click one Azure Container Environment -> Select "Create Container App..." -> Enter a name for the new container app -> Select "Use image from registry" -> Select "Azure Container Registry" -> Select the above created Azure Container Registry.
3. Check whether there is a prompt "No matching resources found" or not.

**Expect:**
There is a prompt "No matching resources found".

**Actual:**
There is no prompt "No matching resources found".
![image](https://github.com/microsoft/vscode-azurecontainerapps/assets/45614674/a2af20f6-12b7-413e-9894-42f67f930eed)

**Comment by MicroFish91** [comment]
Something like this:
![image](https://github.com/microsoft/vscode-azurecontainerapps/assets/40250218/49049658-b676-4f94-aaeb-7f4cc2eada7e)

**Comment by v-ruizh** [comment]
Verified on build 20231006.4, it has been fixed.
