### ISSUE TITLE
[Suggestion] It would be better to add a button "Open Project" in the notification when executing "Deploy Project from Workspace..." command

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurecontainerapps#456]
**OS:** Win10
**Build Version:** 20230920.3
**Regression:** Not a Regression

**Repro Steps:**
1. Open a project folder without a Dockerfile in VS Code.
2. F1 -> Select "Azure Container Apps: Deploy Project from Workspace..." -> A notification pops up.
3. Check whether there is a button "Open Project" in the notification or not.

**Actual:**
There is no button "Open Project" in the notification.
![image](https://github.com/microsoft/vscode-azurecontainerapps/assets/45614674/afe684c4-04bd-41e2-9e12-5dc3364c9549)

**Suggestion:**
It would be better to add a button "Open Project" in the notification.

**Comment by MicroFish91** [comment]
I think this would be fixed by #465

**Comment by v-ruizh** [comment]
Verified on build 20231006.4, it is no longer reproduced.
