### ISSUE TITLE
The validation for the registry name is confusing when creating an Azure Container Registry

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurecontainerapps#459]
**OS:** Win10
**Build Version:** 20230920.3
**Regression:** Previous Build

**Repro Steps:**
1. F1 -> Select "Azure Container Apps: Create Azure Container Registry..." -> Enter a unique name for the new registry, such as "testref" -> Enter.
2. Check whether no error occurs.

**Expect:**
No error occurs.

**Actual:**
An error occurs.
![image](https://github.com/microsoft/vscode-azurecontainerapps/assets/45614674/d9c0c6ad-0ea6-49d3-9624-bedc460fdaf2)

**More Info:**
1. This issue does not reproduce on the previous extension build 20230830.1.
2. This issue also reproduces with the following names, such as "hours", "month".
3. This issue does not reproduce with the following names, such as "test123", "registry", "group".

**Comment by motm32** [comment]
Thanks for submitting this issue! Azure Container Registry names have to be unique within Azure. I tested all of these example names in both the extension and the portal and got the same validation results. Is this issue still occuring?

**Comment by v-ruizh** [comment]
The error still exists when entering ACR name with "test1/test123456789/instance/group/registry/premium/standard/basic...", but the same validation results in the portal and our extension. 
This issue does not reproduce with most names, such as "hours/month/testref...".

**Comment by nturinski** [comment]
I don't think that ACR names have to be globally unique despite what it says in the sdk. I was able to create a registry named "hours" as well and I seriously doubt that I am the first person in the world to create one...

After I create a registry named "hours", I'm getting the error. And If I delete the resource group and registry, I am able to use the name again.

![image](https://github.com/microsoft/vscode-azurecontainerapps/assets/5290572/c06e1a71-2879-4373-9833-f0316ae8e932)

**Comment by MicroFish91** [comment]
Funny story, but we later ended up confirming that Nathan was indeed likely the first person to make a repository named hours 🤣

It's not immediately intuitive because an ACR get requires a resource group, but there seems to also be a globally unique dns lookup that also happens to ensure the name is available.

**Comment by MicroFish91** [comment]
Closing as by-design since the ACR needs to be globally unique as per above.
