### ISSUE TITLE
The activity log is "This may take several minutes..." when deleting the container apps environment

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurecontainerapps#473]
**OS:** Win10
**Build Version:** 20231006.4
**Regression:** Previous release (0.5.1)

**Repro Steps:**
1. Create a new container apps environment.
2. Delete the above container apps environment.
3. Check whether the activity log is "Deleting Container Apps environment 'xxx'... this may take several minutes." when deleting the container apps environment.

**Expect:**
The activity log is "Deleting Container Apps environment 'xxx'... this may take several minutes." when deleting the container apps environment.
![image](https://github.com/microsoft/vscode-azurecontainerapps/assets/57662131/af8e98cf-26a7-4ae2-b253-3a9f20b42e42)

**Actual:**
The activity log is "This may take several minutes..." when deleting the container apps environment.
![image](https://github.com/microsoft/vscode-azurecontainerapps/assets/57662131/1255ef05-375a-4b27-81d4-152e1989ee9d)

**More Info:**
There is also no log "Deleting Container Apps environment 'xxx'... this may take several minutes." in the Output window.
![image](https://github.com/microsoft/vscode-azurecontainerapps/assets/57662131/1616964b-a489-4cac-a970-998b0f670725)

**Comment by nturinski** [comment]
This is by-design. The old text was very long and hard to read. Since the title says "Delete container apps environment," we can assume that the user will know that is what "This may take several minutes..." is referring to.
