### ISSUE TITLE
[Suggestion] It would be better to disable the action "Edit Secret Name..." for the secret already presents in the container app

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurecontainerapps#489]
**OS:** All
**Build Version:** 20231012.2
**Regression:** Not a Regression

**Repro Steps:**
1. Create a container app -> Expand the container app -> Expand Configurations node-> Expand Secrets node.
2. Right click the secret already presents in the container app  -> Click "Edit Secret Name..." -> Type a valid name -> Enter.
3. Check whether no error occurs.

**Actual:**
An error occurs.
<img width="455" alt="Screenshot 2023-10-16 at 14 47 24" src="https://github.com/microsoft/vscode-azurecontainerapps/assets/57662131/c0a51a68-59d4-4be1-9aa6-95b3c68fa443">

**Suggestion:**
It would be better to disable the action "Edit Secret Name..." for the secret already presents in the container app.

**More Info:**
This issue also reproduces after executing actions "Edit Secret Value..." and "Delete Secret...".

**Comment by MicroFish91** [comment]
This is a really good suggestion, we should add some variation of this before the next release.

**Comment by nturinski** [comment]
Fixed by #501
