### ISSUE TITLE
There is no command "Create Container App from Workspace..." in command palette

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurecontainerapps#490]
**OS:** All
**Build Version:** 20231012.2
**Regression:** Not a Regression

**Repro Steps:**
1. Right click one container apps environment and there is one action "Create Container App from Workspace...".
![image](https://github.com/microsoft/vscode-azurecontainerapps/assets/45614674/6cfc72a0-ac41-41e1-830b-e2fa4a249706)
2. F1 to open the command palette.
3. Check whether there is a command "Create Container App from Workspace..." in command palette.

**Expect:**
There is a command "Create Container App from Workspace..." in command palette.

**Actual:**
There is no command "Create Container App from Workspace..." in command palette.
![image](https://github.com/microsoft/vscode-azurecontainerapps/assets/45614674/97b17ac2-e9d0-4d61-9874-2060a379f667)

**Comment by MicroFish91** [comment]
Closing this one as by-design.  There is only one command palette command for this series of commands:
`Deploy Project from Workspace...`
