### ISSUE TITLE
Display the scale rule list of the latest revision when deleting a revision but not a latest one

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurecontainerapps#496]
**OS:** All
**Build Version:** 20231016.3
**Regression:** Not a Regression

**Repro Steps:**
1. Create a container app.
2. Make sure the revision mode is multiple.
3. Create scale rules.
4. F1 -> Click "Delete Scale Rule..." -> Select a container apps environment -> Select a container app -> Select the latest revision -> Select a scale rule -> Cancel.
5. F1 -> Click "Delete Scale Rule..." -> Select a container apps environment -> Select a container app -> Select a revision (Not the latest one).
6. Check the scale rule list.

**Expect:**
Display the scale rule list of the revision selected in step 5.

**Actual:**
Display the scale rule list of the latest revision.
<img width="1044" alt="Screenshot 2023-10-17 at 10 40 39" src="https://github.com/microsoft/vscode-azurecontainerapps/assets/57662131/55633986-240f-4eb3-89fc-cde8a94e87e0">

**Comment by MicroFish91** [comment]
Closed by the above PR
