### ISSUE TITLE
There is no notification after executing "Deploy Image to Azure Container Apps" command

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-azurecontainerapps#509]
**OS:** All
**Build Version:** 20231019.2
**Regression:** Previous Release

**Repro Steps:**
1. Right click this image in Image view -> Push -> Azure -> Select a registry to push.
2. Right click the image in Registry view -> Deploy Image to Azure Container Apps.
4. Check whether there is a notification after executing "Deploy Image to Azure Container Apps" command. 

**Expect:**
There is a notification after executing "Deploy Image to Azure Container Apps" command.
![image](https://github.com/microsoft/vscode-azurecontainerapps/assets/107091828/9dc3e23a-096d-4aa8-9f8b-d5b84ef981b5)

**Actual:**
There is no notification after executing "Deploy Image to Azure Container Apps" command.

**More Info:**
This issue also reproduces when executing "Deploy Image to Azure Container Apps" command for Docker Hub and Generic Registry V2 registries.

**Comment by v-chenzha** [comment]
Verified on the latest build 20231027.2, this issue still reproduces for now. So, reopen it.

There is also **no notification** after creating a new container app.
![image](https://github.com/microsoft/vscode-azurecontainerapps/assets/107091828/4e0dd6dc-1ece-4d5b-8e7b-afe345ff1e86)

**Comment by MicroFish91** [comment]
We now have it respecting the `suppressActivityNotification` setting that you can set in your Azure Resources user setting.  If toggle that, does it cause this to show vs. not show up?

**Comment by v-chenzha** [comment]
This issue does not reproduce when the `suppressActivityNotification` setting is unchecked. So, close it.
