### ISSUE TITLE
[Suggestion] It would be better to remove "add secrets: xxx" from the error message after deleting a secret which has an active revision referencing it

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurecontainerapps#538]
**OS:** All
**Build Version:** 20231030.6

**Repro Steps:**
1. Make sure the revision mode is "Multiple".
2. Add an "Azure queue" scale rule with a new secret created for one container app.
3. Execute "Delete Secret..." action for the above secret.
4. Check whether the error message is clear or not.

**Actual:**
The error message is not clear, it suggests adding a secret.
![image](https://github.com/microsoft/vscode-azurecontainerapps/assets/45614674/b811070b-fc38-48f2-938f-dc30d2551b05)

**Suggestion:**
It would be better to remove "add secrets: xxx" from the error message.

**Comment by MicroFish91** [comment]
Unfortunately the service is throwing this error and we do not want to start changing the wordings on their error messages.
