### ISSUE TITLE
Fail to activate one "Inactive" revision in the container app which created from workspace

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurecontainerapps#549]
**OS:** Win 10
**Build Version:** 20231101.3

**Repro Steps:**
1. Open a [containerapps-albumapi-javascript](https://github.com/azure-samples/containerapps-albumapi-javascript) project in VS Code.
2. Right click one container apps environment -> Select "Create Container App from Workspace..." to create a container app.
3. Change the revision mode to "Multiple" for the above container app.
4. Right click the revision and "Deactivate" it.
5. Right click the above "Inactive" revision and select "Activate" action.
6. Check whether succeeds to activate the "Inactive" revision or not.

**Expect:**
Succeed to activate the "Inactive" revision without any error.

**Actual:**
Fail to activate the "Inactive" revision with an error.
![image](https://github.com/microsoft/vscode-azurecontainerapps/assets/45614674/c1fd6698-1046-4e85-9307-31fbaf992f15)

**Comment by MicroFish91** [comment]
Does waiting for a minute or so and re-running the command let it execute without errors?
