### ISSUE TITLE
Create an API for the `deployWorkspaceProject` command

### ISSUE THREAD

**Issue by motm32** [microsoft/vscode-azurecontainerapps#571]
For the functions in ACA work we have to call this command in order to build an image from a dockerfile and create a container app. After discussion it seemed best to create an API instead of just calling the `executeCommand`.

**Comment by nturinski** [comment]
The ACA extension only needs to pass back the managedEnvironmentId and the registry/image url. 

Refer to this bicep file for the payload: https://github.com/Azure/azure-functions-on-container-apps/blob/main/samples/Biceptemplates/Func_on_ACA_Bicepdeploy.bicep#L63-L86

ACA should _not_ create a container app during this workflow. 

What we need: 
- Enable to pass some options to prevent certain create steps from running 
- Prevent saving local workspace settings that are typically used when deploying workspaces.
