### ISSUE TITLE
Fail to execute command "Azure Container Apps: Activate" with an error from command palette

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurecontainerapps#67]
**OS:** All
**Build Version:** 20220405.6
**Regression:** Not a Regression

**Repro Steps:**

1. F1 -> Azure Container Apps: Activate -> Select a subscription -> Select a container app environment -> Select a container app -> Select a revision.
2. Check whether succeeds to execute command "Azure Container Apps: Activate" directly.

**Expect:**
Succeed to execute command "Azure Container Apps: Activate" directly.

**Actual:**
Continue to perform the next step and fail to execute command "Azure Container Apps: Activate" with an error.
<img width="447" alt="Screen Shot 2022-04-06 at 14 16 23" src="https://user-images.githubusercontent.com/62053665/161938390-961cac76-6611-43b8-80bf-e2062b302bc4.png">

**More Info:**
This issue also reproduces for the commands "Azure Container Apps: Deactivate" and "Azure Container Apps: Restart".

**Comment by v-ruizh** [comment]
This issue also reproduces for the command "Azure Container Apps: Delete Container Apps Environment...".

**Comment by v-chenzha** [comment]
Verified on the latest build [20230309.15](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=59245&view=results), this issue has been fixed for now. So close it.
