### ISSUE TITLE
Directly execute command "Azure Container Apps: Edit Target Port... " and pop up an error from command palette

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurecontainerapps#68]
**OS:** All
**Build Version:** 20220405.6
**Regression:** Not a Regression

**Repro Steps:**

1. F1 -> Azure Container Apps: Edit Target Port... -> Select a subscription -> Select a container app environment -> Select a container app.
2. Check whether continues to perform the next step of selecting the "Ingress".

**Expect:**
Continue to perform the next step of selecting the "Ingress".

**Actual:**
Directly execute command "Azure Container Apps: Edit Target Port... " and pop up an error.
<img width="447" alt="Screen Shot 2022-04-06 at 14 16 23" src="https://user-images.githubusercontent.com/62053665/161938390-961cac76-6611-43b8-80bf-e2062b302bc4.png">

**More Info:**
This issue also reproduces for the commands "Azure Container Apps: Switch Ingress Visibility", "Azure Container Apps: Disable Ingress for Container App" and "Azure Container Apps: Delete Container App Environment".

**Comment by v-ruizh** [comment]
This issue does not reproduce on the main branch build 20230403.1, close it.
