### ISSUE TITLE
Dockerfile path descriptions are too long

### ISSUE THREAD

**Issue by MicroFish91** [microsoft/vscode-azurecontainerapps#684]
We need to figure out a better more condensed way to display the paths.

Example of current:

![image](https://github.com/microsoft/vscode-azurecontainerapps/assets/40250218/aff2565f-3826-45fe-9abb-333f39dbac96)

**Comment by alexweininger** [comment]
Can you display it relative to the open folder?

**Comment by nturinski** [comment]
<img src="https://media4.giphy.com/media/sdlih3BPUik1y/giphy.gif"/>

Dockerfile path description character counts are...
