### ISSUE TITLE
An error occurs when executing "Deploy Workspace to Container App..." action for a container app with "Managed Identity" registry connection method selected

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurecontainerapps#776]
**OS:** All
**Build Version:** 20241019.1
**Regression:** Not a Regression

**Repro Steps:**
1. Create a container app.
2. Open a project [containerapps-albumapi-javascript](https://github.com/azure-samples/containerapps-albumapi-javascript) in VS Code.
3. Right click the above container app -> Execute "Deploy Workspace to Container App..." action with "Managed Identity" registry connection method selected.
4. Check whether no error occurs when executing "Deploy Workspace to Container App..." action for a container app.

**Expect:**
No error occurs when executing "Deploy Workspace to Container App..." action for a container app.

**Actual:**
An error occurs when executing "Deploy Workspace to Container App..." action for a container app.
![Image](https://github.com/user-attachments/assets/6d7c2354-3615-426a-9a98-6a3210faa5bf)

**More Info:**
1. Succeed to deploy workspace project to the container app with the above error.
2. The below dialog pops up if executing "Deploy Workspace to Container App..." action with "Docker Login Credentials" registry connection method selected.
![Image](https://github.com/user-attachments/assets/6140ec4f-f1b2-4c8f-b03f-9da19f7db567)

**Comment by MicroFish91** [comment]
Hi, could you try to repro again with the latest commit on main, I believe this should have been fixed with a previous PR, but I want to confirm.  Thanks!
