### ISSUE TITLE
There is no command "+ Create new registry..." in the command list when asking to select an azure container registry

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurecontainerapps#78]
**OS:** All
**Build Version:** 20220405.6
**Regression:** Not a Regression

**Repro Steps:**

1. Right click a container app environment -> Create Container App -> Type a name -> Select "Azure Container Registries".
2. Check whether there is a command "+ Create new registry..." in the command list.

**Expect:**
There is a command "+ Create new registry..." in the command list.

**Actual:**
There is no command "+ Create new registry..." in the command list.
<img width="558" alt="Screen Shot 2022-04-06 at 18 36 21" src="https://user-images.githubusercontent.com/62053665/161956880-f8948381-a84b-47b3-8684-20c7e5835c72.png">

**Comment by anthonychu** [comment]
Creating a new registry here currently does not make sense because there would be no images in there. However this could change when we look at expanding the deployment commands to build and push images too.
