### ISSUE TITLE
There is no Container Apps option in the list after clicking "Report Issue"

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurecontainerapps#82]
**OS:** All
**Build Version:** 20220405.6
**Regression:** Not a regression

**Repro Steps:**
1. Ensure the Azure Container Apps extension is installed.
2. Navigate to **Azure** view -> Expand **HELP AND FEEDBACK** node -> Click "Report Issue".
3. Check whether there is the Container Apps option in the list.

**Expect:**
There is the Container Apps option in the list.

**Actual:**
There is no Container Apps option in the list.
![image](https://user-images.githubusercontent.com/57662131/161966373-487dcd90-4e21-4e6e-9c5a-c156ee4cf65c.png)

**More Info:**
This issue also reproduces for "Review Issue".

**Comment by nturinski** [comment]
This won't be fixed until we actually release Resource Groups.  I don't think that including Container Apps in the report issue list is worth a release though.
