### ISSUE TITLE
The error is not clear when creating a second container app environment with the same location 

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurecontainerapps#83]
**OS:** All
**Build Version:** 20220405.6
**Regression:** Not a regression

**Repro Steps:**
1. Create a container app environment with a location, such as "East US".
2. Create a new container app environment with the location "East US" again, an error occurs when creating the second container app environment with the location "East US".
3. Check whether the error is clear or not.

**Expect:**
The error is clear, such as "There is only one environment can be created in one location...".

**Actual:**
The error is not clear.
![image](https://user-images.githubusercontent.com/45614674/161968663-17709e17-3cba-4a2a-8591-1b5d75910094.png)

**More Info:**
The new container app environment with other locations can be created successfully.

**Comment by nturinski** [comment]
The error code is `'MaxNumberOfEnvironmentsInSubExceeded'` which we can check for, but based off the error message and code, I feel like the service is checking a different condition.  Like @v-ruizh mentioned, it seems like you can have more than 2 environments as long as you are creating them in different locations.

@anthonychu Know who the right person is to ask about this?

**Comment by nturinski** [comment]
@v-ruizh Are you able to reproduce this still? I was able to create 3 environments in the same location.

**Comment by v-ruizh** [comment]
@nturinski This issue does not reproduce on the latest build 20221008.1, close it.
